spring:
  application:
    name: rag
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
  ai:
#    client:
#      enabled: false

    openai:
      api-key: none
      timeout: 10m
      chat:
        model: llama31
      embedding:
        model: nomic-embed
    vectorstore:
      qdrant:
        initialize-schema: true
        collection-name: docs_llamacpp

    mcp:
      client:
        enabled: true
        name: rag-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC




#logging:
#  level:
#    org.springframework.ai: DEBUG
#    org.springframework.ai.chat: DEBUG
#    org.springframework.ai.embedding: DEBUG
#    com.openai: DEBUG
#    org.springframework.web.reactive.function.client: DEBUG