spring:
  datasource:
    url: jdbc:postgresql://10.0.0.227:5432/rag
    username: postgres
    password: postgres
  ai:
    openai:
      chat:
        base-url: http://10.0.0.44:8080/v1
      embedding:
        base-url: http://10.0.0.44:8081/v1
    vectorstore:
      qdrant:
        host: 10.0.0.227
        port: 6334
    mcp:
      client:
        streamable-http:
          connections:
            server1:
              url: http://localhost:8075
              endpoint: /api/mcp
management:
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
      zipkin:
        endpoint: http://10.0.0.227:9411/api/v2/spans