spring:
  application:
    name: rag
  datasource:
    url: jdbc:postgresql://localhost:5332/rag
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:latest
      embedding:
        options:
          model: nomic-embed-text:latest
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: docs_random_llama3.2

